import fs from 'node:fs';
import path from 'node:path';
import { runClaude } from '../src/claude.mjs';
import { ROOT } from '../src/server.mjs';
import { UUID } from '../src/core.mjs';
const id=process.argv[2];
if(!UUID.test(id||''))throw new Error('Usage: npm run review -- <session-id>');
const dir=path.join(ROOT,'recordings',id);
const session=JSON.parse(fs.readFileSync(path.join(dir,'session.json'),'utf8'));
if(session.status!=='ended')throw new Error('End the call before requesting editorial review.');
const events=fs.readFileSync(path.join(dir,'events.jsonl'),'utf8').trim().split('\n').filter(Boolean).map(JSON.parse).filter(e=>!['text','audio-produced'].includes(e.type));
const note={type:'object',additionalProperties:false,required:['turn_ids','rationale'],properties:{turn_ids:{type:'array',items:{type:'string'}},rationale:{type:'string'}}};
const schema={type:'object',additionalProperties:false,required:['summary','highlights','proposed_cuts','uncertainties','visual_direction'],properties:{summary:{type:'string'},highlights:{type:'array',items:note},proposed_cuts:{type:'array',items:note},uncertainties:{type:'array',items:{type:'string'}},visual_direction:{type:'string'}}};
const prompt=JSON.stringify({session,events});
if(prompt.length>600000)throw new Error('This session is too large for one review. Split it into source-linked chapters first.');
const result=await runClaude({system:fs.readFileSync(path.join(ROOT,'prompts/review.md'),'utf8'),prompt,model:session.actual_model || session.settings.claude_model,effort:session.settings.claude_effort,schema});
const known=new Set(session.turns.map(t=>t.id));
for(const item of [...result.structured.highlights,...result.structured.proposed_cuts])if(!item.turn_ids.length||item.turn_ids.some(id=>!known.has(id)))throw new Error('Review referenced an unknown or empty source turn. Originals are unchanged.');
const destination=path.join(dir,`annotations-${new Date().toISOString().replace(/[:.]/g,'-')}.json`);
fs.writeFileSync(destination,JSON.stringify({status:'proposed-for-human-review',source_session:id,created_at:new Date().toISOString(),...result.structured},null,2),{flag:'wx',mode:0o600});
console.log(destination);
